version: '3.3'    
services:
  workflow-manager:
    build:
      context: ./
      dockerfile: ./src/GEOrchestrator.WorkflowManager/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8080"
    environment:
        AWS_REGION: ${AWS_REGION}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
        OBJECT_REPOSITORY_PROVIDER: ${OBJECT_REPOSITORY_PROVIDER}
        AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
        JOB_REPOSITORY_PROVIDER: ${JOB_REPOSITORY_PROVIDER}
        PARAMETER_REPOSITORY_PROVIDER: ${PARAMETER_REPOSITORY_PROVIDER}
        ARTIFACT_REPOSITORY_PROVIDER: ${ARTIFACT_REPOSITORY_PROVIDER}
        WORKFLOW_REPOSITORY_PROVIDER: ${WORKFLOW_REPOSITORY_PROVIDER}
        TASK_REPOSITORY_PROVIDER: ${TASK_REPOSITORY_PROVIDER}
        EXECUTION_STEP_REPOSITORY_PROVIDER: ${EXECUTION_STEP_REPOSITORY_PROVIDER}
        EXECUTION_STEP_MESSAGE_REPOSITORY_PROVIDER: ${EXECUTION_STEP_MESSAGE_REPOSITORY_PROVIDER}
        EXECUTION_REPOSITORY_PROVIDER: ${EXECUTION_REPOSITORY_PROVIDER}
        WORKFLOW_API_URL: ${WORKFLOW_API_URL}
        CONTAINER_PROVIDER: ${CONTAINER_PROVIDER}
        FARGATE_REGION: ${FARGATE_REGION}
        FARGATE_EXECUTION_ROLE_ARN: ${FARGATE_EXECUTION_ROLE_ARN}
        FARGATE_CLUSTER_NAME: ${FARGATE_CLUSTER_NAME}
        FARGATE_SUBNET_ID: ${FARGATE_SUBNET_ID}
        FARGATE_SECURITY_GROUP_ID: ${FARGATE_SECURITY_GROUP_ID}
  task-manager:
    build:
      context: ./
      dockerfile: ./src/GEOrchestrator.TaskManager/Dockerfile
    ports:
      - "8001:8080"
    environment:
        AWS_REGION: ${AWS_REGION}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
        OBJECT_REPOSITORY_PROVIDER: ${OBJECT_REPOSITORY_PROVIDER}
        AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
        PARAMETER_REPOSITORY_PROVIDER: ${PARAMETER_REPOSITORY_PROVIDER}
        ARTIFACT_REPOSITORY_PROVIDER: ${ARTIFACT_REPOSITORY_PROVIDER}
        WORKFLOW_REPOSITORY_PROVIDER: ${WORKFLOW_REPOSITORY_PROVIDER}
        TASK_REPOSITORY_PROVIDER: ${TASK_REPOSITORY_PROVIDER}
        EXECUTION_STEP_REPOSITORY_PROVIDER: ${EXECUTION_STEP_REPOSITORY_PROVIDER}
        EXECUTION_STEP_MESSAGE_REPOSITORY_PROVIDER: ${EXECUTION_STEP_MESSAGE_REPOSITORY_PROVIDER}
        EXECUTION_REPOSITORY_PROVIDER: ${EXECUTION_REPOSITORY_PROVIDER}
        WORKFLOW_API_URL: ${WORKFLOW_API_URL}
        CONTAINER_PROVIDER: ${CONTAINER_PROVIDER}
        FARGATE_REGION: ${FARGATE_REGION}
        FARGATE_EXECUTION_ROLE_ARN: ${FARGATE_EXECUTION_ROLE_ARN}
        FARGATE_CLUSTER_NAME: ${FARGATE_CLUSTER_NAME}
        FARGATE_SUBNET_ID: ${FARGATE_SUBNET_ID}
        FARGATE_SECURITY_GROUP_ID: ${FARGATE_SECURITY_GROUP_ID}